<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="imu_size" value="0.01"/>

    <xacro:property name="lidar_size" value="0.025"/>

    <link name="imu_link">
        <visual>
            <origin xyz="${wheelbase_length / 2} 0 ${wheel_diameter}" rpy="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
            <material name="imu_material"/>
        </visual>

        <sensor name="my_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <plugin name="my_imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                <!-- Will publish to /imu_data -->
                <namespace></namespace>
                <remapping>~/out:=imu_data</remapping>
                </ros>
            </plugin>
        </sensor>
    </link>

    <joint name="base_to_imu" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <link name="sllidar_base_link">
        <visual>
            <origin xyz="${wheelbase_length / 2} 0 ${wheel_diameter * 1.5}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${lidar_size}" radius="${lidar_size}"/>
            </geometry>
            <material name="lidar_material"/>
        </visual>

        <sensor name="lidar" type="gpu_ray">
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-${pi / 2}</min_angle>
                        <max_angle>${pi / 2}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
              <!-- Using gazebo's noise instead of plugin's -->
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <!-- Using gazebo's update rate instead of plugin's -->
            <update_rate>30</update_rate>
        
            <plugin name="my_lidar" filename="libgazebo_ros_ray_sensor.so">
                <!-- Change namespace and output topic so published topic is /rrbot/laser/scan -->
                <ros>
                    <namespace>/rrbot/laser</namespace>
                    <remapping>~/out:=scan</remapping>
                </ros>
              <!-- Set output to sensor_msgs/LaserScan to get same output type as gazebo_ros_laser -->
                <output_type>sensor_msgs/LaserScan</output_type>
              <!-- <frame_name> ommited, will default to hokuo_link -->
            </plugin>
        </sensor>
    </link>

    <joint name="base_to_lidar" type="fixed">
        <parent link="base_link"/>
        <child link="sllidar_base_link"/>
    </joint>
</robot>
