<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="imu_size" value="0.01"/>
    <xacro:property name="lidar_size" value="0.025"/>

    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
            <material name="imu_material"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
        </inertial>
    </link>

    <gazebo reference="imu_link">
        <sensor name="my_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <plugin name="my_imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                    <remapping>~/out:=imu_data</remapping>
                </ros>
            </plugin>
        </sensor>

        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="base_to_imu" type="fixed">
        <origin xyz="0 0 ${wheel_diameter}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <link name="sllidar_base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${lidar_size}" radius="${lidar_size}"/>
            </geometry>
            <material name="lidar_material"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${lidar_size}" radius="${lidar_size}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.2"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
        </inertial>
    </link>

    <gazebo reference="sllidar_base_link">
        <sensor name="sensor_gpu_ray" type="ray">
            <visualize>true</visualize>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1.0</resolution>
                        <min_angle>-${pi}</min_angle>
                        <max_angle>${pi}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12.0</max>
                </range>
            </ray>
            <always_on>true</always_on>
    
            <plugin name="laser_scan_plugin" filename="libgazebo_ros_ray_sensor.so">
                <output_type>sensor_msgs/LaserScan</output_type>
                <frameName>sllidar_base_link</frameName> 
                <topicName>/scan</topicName>
                <remapping>~/out:=scan</remapping>
                <updateRate>30.0</updateRate> 
            </plugin>
        </sensor>

        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="base_to_lidar" type="fixed">
        <origin xyz="${wheelbase_length / 2} 0 ${wheel_diameter * 1.5}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="sllidar_base_link"/>
    </joint>
</robot>
