<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smartcar">
    <xacro:property name="chassis_thickness" value="0.0125"/>
    <xacro:property name="wheelbase_length" value="0.257"/>
    <xacro:property name="wheelbase_width" value="0.17"/>

    <xacro:include filename="wheels.xacro"/>
    <xacro:include filename="materials.xacro"/>

    <link name="base_link">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_to_chassis" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${wheelbase_length} ${wheelbase_width} ${chassis_thickness}"/>
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        </visual>
    </link>

    <link name="base_footprint">
        <visual>
            <geometry>
                <box size="${wheelbase_length * 2} ${wheelbase_width * 2} ${wheel_diameter * 2}"/>
            </geometry>
            <material name="footprint_material"/>
            <origin xyz="0 0 ${wheel_diameter}" rpy="0 0 0" />
        </visual>
    </link>

    <joint name="base_to_footprint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <xacro:front_wheel prefix="left" parent="base_link" x="${wheelbase_length / 2}" y="${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="${wheel_width / 2}"/>
    <xacro:front_wheel prefix="right" parent="base_link" x="${wheelbase_length / 2}" y="-${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="-${wheel_width / 2}"/>
    
    <xacro:rear_wheel prefix="left" parent="base_link" x="-${wheelbase_length / 2}" y="${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="${wheel_width / 2}"/>
    <xacro:rear_wheel prefix="right" parent="base_link" x="-${wheelbase_length / 2}" y="-${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="-${wheel_width / 2}"/>

    <xacro:include filename="sensors.xacro"/>
</robot>
