<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="wheel_diameter" value="0.064"/>
    <xacro:property name="wheel_radius" value="${wheel_diameter / 2}"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_oriantation" value="${90 * (pi / 180)}"/>
    <xacro:property name="steer_link_size" value="0.01"/>

    <xacro:macro name="front_wheel" params="prefix parent x y z wheel_offset">
        <joint name="front_${prefix}_wheel_steer_joint" type="revolute">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="front_${prefix}_wheel_steer_link"/>
            <axis xyz="0 0 1"/>
            <limit lower="-${45 * (pi / 180)}" upper="${45 * (pi / 180)}" effort="10" velocity="1"/>
        </joint>

        <link name="front_${prefix}_wheel_steer_link">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <visual>
                <geometry>
                    <box size="${steer_link_size} ${steer_link_size} ${steer_link_size}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${steer_link_size} ${steer_link_size} ${steer_link_size}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>

            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.00005" ixy="0.0" ixz="0.0" iyy="0.00005" iyz="0.0" izz="0.00005"/>
            </inertial>
        </link>

        <gazebo reference="front_${prefix}_wheel_steer_link">
            <material>Gazebo/Red</material>
        </gazebo>

        <joint name="front_${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="front_${prefix}_wheel_steer_link"/>
            <child link="front_${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="front_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_oriantation} 0 0"/>
                <material name="wheel_material"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_oriantation} 0 0"/>
            </collision>

            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
            </inertial>
        </link>

        <gazebo reference="front_${prefix}_wheel_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="back_wheel" params="prefix parent x y z wheel_offset">
        <joint name="back_${prefix}_wheel_joint" type="continuous">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="back_${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="back_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_oriantation} 0 0"/>
                <material name="wheel_material"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_oriantation} 0 0"/>
            </collision>

            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
            </inertial>
        </link>

        <gazebo reference="back_${prefix}_wheel_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>
</robot>
