<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="wheel_diameter" value="0.064"/>
    <xacro:property name="wheel_radius" value="${wheel_diameter / 2}"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_oriantation" value="${90 * (pi / 180)}"/>


    <xacro:macro name="front_wheel" params="prefix parent x y z wheel_offset">
        <joint name="front_${prefix}_wheel_steer_joint" type="revolute">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="front_${prefix}_wheel_steer_link"/>
            <axis xyz="0 0 1"/>
            <limit lower="-${45 * (pi / 180)}" upper="${45 * (pi / 180)}" effort="10" velocity="1"/>
        </joint>

        <link name="front_${prefix}_wheel_steer_link">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </link>

        <joint name="front_${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="front_${prefix}_wheel_steer_link"/>
            <child link="front_${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="front_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_oriantation} 0 0"/>
                <material name="wheel_material"/>
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="rear_wheel" params="prefix parent x y z wheel_offset">
        <joint name="rear_${prefix}_wheel_joint" type="continuous">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="rear_${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="rear_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_oriantation} 0 0" />
                <material name="wheel_material"/>
            </visual>
        </link>
    </xacro:macro>
</robot>